apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: {{ .Values.clusterName }}-worker-{{ .Values.machineNameSuffix }}-{{ .Values.availabilityZone }}
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-worker-{{ .Values.machineNameSuffix }}-{{ .Values.availabilityZone }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-worker-{{ .Values.machineNameSuffix }}-{{ .Values.availabilityZone }}
        cpu-instance-type: {{ .Values.instanceType }}
        cpu-type-suffix: {{ .Values.machineNameSuffix }}
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
          cpu-instance-type: {{ .Values.instanceType }}
          cpu-type-suffix: {{ .Values.machineNameSuffix }}
      providerSpec:
        value:
          kind: AWSMachineProviderConfig
          apiVersion: machine.openshift.io/v1beta1
          instanceType: {{ .Values.instanceType }}
          ami:
            id: {{ .Values.amiId | quote }}
          blockDevices:
            - ebs:
                encrypted: true
                volumeSize: {{ .Values.rootVolume.size }}
                volumeType: {{ .Values.rootVolume.type }}
                {{- if eq .Values.rootVolume.type "gp3" }}
                iops: {{ .Values.rootVolume.iops }}
                {{- else }}
                iops: 0
                {{- end }}
          placement:
            availabilityZone: {{ .Values.availabilityZone }}
            region: {{ .Values.region }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - "{{ .Values.infraID }}-node"
            - filters:
                - name: tag:Name
                  values:
                    - "{{ .Values.infraID }}-lb"
          subnet:
            filters:
              - name: tag:Name
                values:
                  - "{{ .Values.infraID }}-subnet-private-{{ .Values.availabilityZone }}"
          iamInstanceProfile:
            id: "{{ .Values.infraID }}-worker-profile"
          tags:
            - name: kubernetes.io/cluster/{{ .Values.infraID }}
              value: owned
            - name: cpu-worker-node
              value: "true"
            - name: cpu-instance-type
              value: {{ .Values.instanceType }}
          userDataSecret:
            name: worker-user-data
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
