# AWS g6e.2xlarge GPU Configuration
# 1x NVIDIA L40S (48GB GDDR6)
# 8 vCPUs, 64 GB RAM
# Cost: ~$2.24/hour (on-demand, us-east-1)

machineNameSuffix: "g6e"
instanceType: g6e.2xlarge
replicas: 1

rootVolume:
  size: 120
  type: gp3
  iops: 3000

gpu:
  count: 1
  memoryMb: 49152
  vCPU: 8
